# Generated by Django 4.2.4 on 2023-09-04 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subActivities', '0006_rename_percentege_subactivities_percentage'),
        ('tasks', '0004_alter_task_percentege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='percentege',
            new_name='percentage',
        ),
        migrations.AlterField(
            model_name='task',
            name='subActivity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='subActivities.subactivities'),
        ),
    ]
