# Generated by Django 4.2.4 on 2023-08-31 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_alter_task_percentege'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=255, verbose_name='descripcion')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('noenviado', 'No Enviado')], default='noenviado', max_length=10, verbose_name='Estado')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de subida')),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(default='/toTask.jpg', upload_to='archivos_entrega/')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidence.evidence')),
            ],
        ),
    ]
