# Generated by Django 4.2.4 on 2023-08-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='files',
            field=models.ManyToManyField(related_name='evidences', to='evidence.file'),
        ),
    ]
