# Generated by Django 4.2.4 on 2023-08-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_activities_user'),
        ('subActivities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subactivities',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.activities'),
        ),
    ]
