# Generated by Django 4.2.4 on 2023-08-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subActivities', '0002_subactivities_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subactivities',
            name='percentege',
            field=models.FloatField(default=None, verbose_name='Porcentaje'),
        ),
    ]
