# Generated by Django 4.2.4 on 2023-09-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subActivities', '0005_alter_subactivities_percentege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subactivities',
            old_name='percentege',
            new_name='percentage',
        ),
    ]
