# Generated by Django 4.2.4 on 2023-09-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_activities_user'),
        ('subActivities', '0006_rename_percentege_subactivities_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subactivities',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subactivities', to='base.activities'),
        ),
    ]
